[land_model_spectrum_V1]
git-tree-sha1 = "ea4a9eb822a62542d0cedd7a0921d620dde47af7"
lazy = true

    [[land_model_spectrum_V1.download]]
    sha256 = "ee0ee97c013317d5535868db08a0929e4f5dbaef2d2003ed61485003e5302386"
    url = "ftp://fluo.gps.caltech.edu/XYZT_CLIMA_LUT/LandModel/land_model_spectrum_V1.tar.gz"
    [[land_model_spectrum_V1.download]]
    sha256 = "ee0ee97c013317d5535868db08a0929e4f5dbaef2d2003ed61485003e5302386"
    url = "https://github.com/Yujie-W/ResearchArtifacts/raw/wyujie/LandModel/land_model_spectrum_V1.tar.gz"
