name = "Emerald"
uuid = "b4c4a1c9-ad73-451c-9fca-9e2aae930537"
authors = ["Yujie Wang <jesiner@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"
